#!/usr/bin/env python3
"""Inline the ingest-news Edge Function into a single pasteable file.

WHY THIS EXISTS
Deploying an Edge Function normally means `supabase functions deploy`, which
needs the Supabase CLI. This Mac has no CLI, no Homebrew, no Node and no Deno,
so the only route left is the dashboard's function editor — and that is a much
happier place to paste one file than five.

The function's four local imports (`../_shared/*.ts`) have no imports of their
own, so inlining is a concatenation rather than a dependency walk. The `npm:`
import stays untouched: Deno resolves that at runtime on Supabase.

The bundle is a BUILD ARTIFACT, never the source of truth. Re-run this after
any change under supabase/functions/ rather than editing the output.

    python3 scripts/bundle-edge-function.py
    → dist/ingest-news.bundled.ts
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENTRY = os.path.join(ROOT, "supabase/functions/ingest-news/index.ts")
SHARED = os.path.join(ROOT, "supabase/functions/_shared")
OUT = os.path.join(ROOT, "dist/ingest-news.bundled.ts")

LOCAL_IMPORT = re.compile(
    r'^import\s*\{([^}]*)\}\s*from\s*"\.\./_shared/([\w.-]+)"\s*$', re.M)


def strip_exports(src: str) -> str:
    """`export function foo` → `function foo`."""
    return re.sub(r"^export\s+", "", src, flags=re.M)


def wrap(name: str, body: str, exports: list) -> str:
    """Give each module its own scope and hand back only what was imported.

    Flattening everything into one scope looked simpler until two modules
    turned out to declare a helper called `env` — in Deno that is a redeclaration
    error, and had the bundle been pasted as-is the function would not have
    booted. An IIFE per module removes the whole class of collision instead of
    renaming symbols one at a time.
    """
    indented = "\n".join(("  " + ln) if ln.strip() else ln for ln in body.splitlines())
    returned = ", ".join(exports)
    rule = "─" * max(4, 44 - len(name))
    return (f"// ─── inlined from _shared/{name} {rule}\n"
            f"const {{ {returned} }} = (() => {{\n{indented}\n"
            f"  return {{ {returned} }}\n}})()")


def main() -> int:
    if not os.path.exists(ENTRY):
        print("entry point missing:", ENTRY, file=sys.stderr)
        return 1
    entry = open(ENTRY, encoding="utf-8").read()

    found = LOCAL_IMPORT.findall(entry)
    if not found:
        print("no ../_shared imports found — has the entry point changed?", file=sys.stderr)
        return 1

    parts, names = [], []
    for raw_names, name in found:
        names.append(name)
        exports = [n.strip() for n in raw_names.split(",") if n.strip()]
        path = os.path.join(SHARED, name)
        if not os.path.exists(path):
            print("missing shared module:", path, file=sys.stderr)
            return 1
        body = strip_exports(open(path, encoding="utf-8").read())
        # A shared module with imports of its own would need a real dependency
        # walk; refuse rather than emit something subtly broken.
        if re.search(r"^import\s", body, re.M):
            print(f"{name} has imports of its own — this bundler cannot handle that",
                  file=sys.stderr)
            return 1
        # Top-level await would need an async IIFE and a different call site.
        if re.search(r"^\s*(?:const|let|var)?\s*.*\bawait\b", body, re.M) and \
           not re.search(r"(async\s+function|=>\s*\{|async\s*\()", body):
            print(f"{name} appears to use top-level await — refusing", file=sys.stderr)
            return 1
        missing = [e for e in exports if not re.search(r"\b" + re.escape(e) + r"\b", body)]
        if missing:
            print(f"{name} does not define: {', '.join(missing)}", file=sys.stderr)
            return 1
        parts.append(wrap(name, body, exports))

    # Drop the local imports; keep npm:/https: ones where they are.
    entry_body = LOCAL_IMPORT.sub("", entry)
    npm_imports = re.findall(r'^import .*from\s*"(?:npm:|https:)[^"]*"\s*$', entry_body, re.M)
    entry_body = re.sub(r'^import .*from\s*"(?:npm:|https:)[^"]*"\s*$', "", entry_body, flags=re.M)

    header = (
        "// GENERATED by scripts/bundle-edge-function.py — do not edit.\n"
        "// Single-file build of supabase/functions/ingest-news for pasting into\n"
        "// the Supabase dashboard when no CLI is available. Edit the sources under\n"
        "// supabase/functions/ and re-run the script.\n\n"
    )
    out = header + "\n".join(npm_imports) + "\n\n" + "\n\n".join(parts) + "\n\n" \
        + "// ─── entry point ───────────────────────────────────────────\n" \
        + strip_exports(entry_body).strip() + "\n"

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w", encoding="utf-8").write(out)

    print(f"✓ {os.path.relpath(OUT, ROOT)}")
    print(f"  {len(names)} module(s) inlined: {', '.join(names)}")
    print(f"  {len(out.splitlines())} lines, {len(out.encode('utf-8'))} bytes")
    leftover = re.findall(r'^import .*$', out, re.M)
    print(f"  remaining imports (must all be npm:/https:): {leftover or 'none'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
